# Generated by Django 4.1.2 on 2022-10-12 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mymodelwithfigure_person_delete_choice_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModelWithFigure',
        ),
    ]
