# Generated by Django 4.0 on 2022-12-08 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_sensor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dreamreal',
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
    ]
