# Generated by Django 4.0 on 2022-12-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daqhat',
            name='boardNumber',
            field=models.IntegerField(null=True, verbose_name=50),
        ),
        migrations.AlterField(
            model_name='daqhat',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
