# Generated by Django 4.0 on 2022-12-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_daqhat_boardnumber_alter_daqhat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daqhat',
            name='boardNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
