# Generated by Django 4.0 on 2022-12-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_daqhat_boardnumber_alter_person_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='daqhat',
            name='channels',
            field=models.IntegerField(null=True),
        ),
    ]
