# Generated by Django 4.0 on 2022-12-14 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_daqhat_scan_rate_alter_daqhat_channels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daqhat',
            name='channels',
        ),
    ]
