# Generated by Django 4.0 on 2022-12-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_daqhat_channels'),
    ]

    operations = [
        migrations.AddField(
            model_name='daqhat',
            name='channels',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
