# Generated by Django 4.0 on 2022-12-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_daqhat_boardnumber_remove_daqhat_channels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daqhat',
            name='input_mode',
            field=models.CharField(choices=[('SE', 'Single-ended'), ('DIFF', 'Differential')], default='', max_length=100),
        ),
    ]
