# Generated by Django 4.0 on 2022-12-14 14:18

import daqhats.hats
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_daqhat_input_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daqhat',
            name='options',
            field=models.CharField(choices=[('DEFAULT', 'Default'), (daqhats.hats.OptionFlags['CONTINUOUS'], 'Continuous')], default='', max_length=100),
        ),
    ]
