# Generated by Django 4.0 on 2022-12-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_daqhat_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='daqhat',
            name='channels',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='daqhat',
            name='options',
            field=models.CharField(choices=[('DEFAULT', 'Default'), ('CONTINUOUS', 'Continuous')], default='', max_length=100),
        ),
    ]
