# Generated by Django 4.0 on 2022-12-19 10:26

import daqhats.hats
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_daqhat_channels_alter_daqhat_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='daqhat',
            name='daq_type',
            field=models.CharField(choices=[(daqhats.hats.HatIDs['MCC_118'], 'MCC_118'), (daqhats.hats.HatIDs['MCC_128'], 'MCC_128'), (daqhats.hats.HatIDs['MCC_134'], 'MCC_134'), (daqhats.hats.HatIDs['MCC_152'], 'MCC_152'), (daqhats.hats.HatIDs['MCC_172'], 'MCC_172')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='daqhat',
            name='options',
            field=models.CharField(choices=[(daqhats.hats.HatIDs['MCC_118'], 'MCC_118'), (daqhats.hats.HatIDs['MCC_128'], 'MCC_128'), (daqhats.hats.HatIDs['MCC_134'], 'MCC_134'), (daqhats.hats.HatIDs['MCC_152'], 'MCC_152'), (daqhats.hats.HatIDs['MCC_172'], 'MCC_172')], default='', max_length=100),
        ),
    ]
