# Generated by Django 4.0 on 2022-12-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_daqhat_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daqhat',
            name='daq_type',
            field=models.CharField(choices=[('DEFAULT', 'Default'), ('CONTINUOUS', 'Continuous')], default='', max_length=100),
        ),
    ]
