# Generated by Django 4.0 on 2022-12-19 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_daqhat_daq_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalogInputRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('mcc_118', models.CharField(default='MCC_118', max_length=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='daqhat',
            name='daq_type',
        ),
        migrations.AddField(
            model_name='daqhat',
            name='analog_input_range',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.analoginputrange'),
        ),
    ]
