# Generated by Django 4.0 on 2022-12-19 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_analoginputrange_remove_daqhat_daq_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analoginputrange',
            name='name',
            field=models.CharField(default='Default', max_length=50),
        ),
        migrations.AlterField(
            model_name='daqhat',
            name='analog_input_range',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.analoginputrange'),
        ),
    ]
