# Generated by Django 4.0 on 2022-12-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_analoginputrange_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analoginputrange',
            name='mcc_118',
        ),
        migrations.AddField(
            model_name='analoginputrange',
            name='output_range',
            field=models.CharField(choices=[('MCC_118', 'MCC_118'), ('MCC_128', 'MCC_128'), ('MCC_134', 'MCC_134'), ('MCC_152', 'MCC_152'), ('MCC_172', 'MCC_172')], default='MCC_118', max_length=100),
        ),
    ]
