# Generated by Django 4.0 on 2022-12-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_analoginputrange_mcc_118_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analoginputrange',
            name='output_range',
        ),
        migrations.AlterField(
            model_name='analoginputrange',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
