# Generated by Django 4.0 on 2022-12-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_analoginputrange_output_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analoginputrange',
            name='output_range',
            field=models.CharField(choices=[('MCC_118', 'MCC_118'), ('MCC_128', 'MCC_128'), ('MCC_134', 'MCC_134'), ('MCC_152', 'MCC_152'), ('MCC_172', 'MCC_172')], default='', max_length=100),
        ),
    ]
