# Generated by Django 4.0 on 2022-12-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_daqhat_daq_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='daqhat',
            name='read_request_size',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='daqhat',
            name='daq_type',
            field=models.CharField(choices=[('MCC_118', 'MCC 118'), ('MCC_128', 'MCC 128'), ('MCC_134', 'MCC 134'), ('MCC_152', 'MCC 152'), ('MCC_172', 'MCC 172')], default='', max_length=100),
        ),
    ]
