# Generated by Django 4.0 on 2022-12-19 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_daqhat_read_request_size_alter_daqhat_daq_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daqhat',
            name='analog_input_range',
        ),
        migrations.DeleteModel(
            name='AnalogInputRange',
        ),
    ]
