# Generated by Django 4.0 on 2022-12-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_remove_daqhat_analog_input_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daqhat',
            name='input_range',
            field=models.CharField(choices=[('BIP_10V', '10V input range'), ('BIP_5V', '5V input range'), ('BIP_2V', '2V input range'), ('BIP_1V', '1V input range')], default='10V input range', max_length=100),
        ),
        migrations.AddField(
            model_name='daqhat',
            name='samples_per_channel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='daqhat',
            name='timeout',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='daqhat',
            name='channels',
            field=models.CharField(default='0,1,2,3', max_length=50),
        ),
        migrations.AlterField(
            model_name='daqhat',
            name='daq_type',
            field=models.CharField(choices=[('MCC_118', 'MCC 118'), ('MCC_128', 'MCC 128'), ('MCC_134', 'MCC 134'), ('MCC_152', 'MCC 152'), ('MCC_172', 'MCC 172')], default='MCC 128', max_length=100),
        ),
        migrations.AlterField(
            model_name='daqhat',
            name='input_mode',
            field=models.CharField(choices=[('SE', 'Single-ended'), ('DIFF', 'Differential')], default='Single-ended', max_length=100),
        ),
        migrations.AlterField(
            model_name='daqhat',
            name='name',
            field=models.CharField(default='Default', max_length=50),
        ),
        migrations.AlterField(
            model_name='daqhat',
            name='options',
            field=models.CharField(choices=[('DEFAULT', 'Default'), ('CONTINUOUS', 'Continuous')], default='Default', max_length=100),
        ),
        migrations.AlterField(
            model_name='daqhat',
            name='scan_rate',
            field=models.FloatField(default=1000.0),
        ),
    ]
