# Generated by Django 4.0 on 2022-12-20 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_daqhat_daq_type_alter_daqhat_read_request_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='List of the last 10 logs', max_length=100)),
                ('log0', models.CharField(default='', max_length=100)),
                ('log1', models.CharField(default='', max_length=100)),
                ('log2', models.CharField(default='', max_length=100)),
                ('log3', models.CharField(default='', max_length=100)),
                ('log4', models.CharField(default='', max_length=100)),
                ('log5', models.CharField(default='', max_length=100)),
                ('log6', models.CharField(default='', max_length=100)),
                ('log7', models.CharField(default='', max_length=100)),
                ('log8', models.CharField(default='', max_length=100)),
                ('log9', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='daqhat',
            name='log_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.loglist'),
        ),
    ]
