# Generated by Django 4.0 on 2022-12-21 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_loglist_daqhat_log_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daqhat',
            name='log_list',
        ),
        migrations.DeleteModel(
            name='LogList',
        ),
    ]
